// Code generated by file2byteslice. DO NOT EDIT.
// (gofmt is fine after generating)

package shader

var Circle = []byte("// +build ignore\r\n\r\npackage shader\r\n\r\nvar Translate vec2\r\nvar Size vec2\r\n\r\nfunc Fragment(position vec4, texCoord vec2, color vec4) vec4 {\r\n\r\n\t// vec2 st = gl_FragCoord.xy/u_resolution;\r\n\tst := (position.xy / Size) - (Translate / Size)\r\n\r\n\tpixel := 1.0 / Size.x\r\n\r\n\t// The DISTANCE from the pixel to the center\r\n\td := distance(st, vec2(0.5))\r\n\r\n\tr := 0.5 - pixel\r\n\r\n\t// // falloff\r\n\t// // 0.01 for large (r>=100.0)\r\n\t// // 0.1 for small (r=5.0)\r\n\t// low1 := 5.0\r\n\t// high1 := 100.0\r\n\t// low2 := 0.9\r\n\t// high2 := 0.99\r\n\t// f := clamp(Size.x, low1, high1)\r\n\t// f = low2 + (f-low1)*(high2-low2)/(high1-low1)\r\n\t// f = 1 - f\r\n\tf := pixel\r\n\r\n\tc := smoothstep(r, r-f, d)\r\n\treturn vec4(c)\r\n}\r\n")
